erDiagram
    USER 1 to 0+ ORGANIZER: cria
    ORGANIZER 1 to 1+ PLAYLIST_INPUT: recebe
    ORGANIZER 1 to 1+ PLAYLIST_OUTPUT: gera
    PLAYLIST_OUTPUT 1+ to 1 PLAYLIST_OUTPUT_GENRE: filtra
    PLAYLIST_OUTPUT_GENRE 1 to 1+ GENRE: filtra
    PLAYLIST_OUTPUT 1+ to 1 PLAYLIST_OUTPUT_ARTIST: filtra
    PLAYLIST_OUTPUT_ARTIST 1 to 1+ ARTIST: filtra
    PLAYLIST_OUTPUT 1 to 1+ PLAYLIST_OUTPUT_YEAR: filtra

    USER {
        guid id PK
        string email
        string password
    }
    ORGANIZER {
        guid id PK
        string name
        guid user_id FK
    }
    PLAYLIST_INPUT {
        guid id PK
        string playlist_id
    }
    PLAYLIST_OUTPUT {
        guid id PK
        string name
        guid organizer_id FK
    }
    GENRE {
        int id PK
        string name UK
    }
    ARTIST {
        int id PK
        string name UK
    }
    PLAYLIST_OUTPUT_YEAR {
        guid id PK
        guid playlist_output_id FK
        int year
    }
    PLAYLIST_OUTPUT_GENRE {
        guid playlist_output_id FK, PK
        int genre_id FK, PK
    }
    PLAYLIST_OUTPUT_ARTIST {
        guid playlist_output_id FK, PK
        int artist_id FK, PK
    }