// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sptf.Data;

#nullable disable

namespace Sptf.Data.Migrations
{
    [DbContext(typeof(SpotinizerContext))]
    [Migration("20260111045314_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FilterOperationOrganizer", b =>
                {
                    b.Property<Guid>("FilterOperationsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizersId")
                        .HasColumnType("uuid");

                    b.HasKey("FilterOperationsId", "OrganizersId");

                    b.HasIndex("OrganizersId");

                    b.ToTable("FilterOperationOrganizer");
                });

            modelBuilder.Entity("Sptf.Domain.Models.FilterOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("FilterOperations");
                });

            modelBuilder.Entity("Sptf.Domain.Models.OperationParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FilterOperationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsList")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SequencePosition")
                        .HasColumnType("integer");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FilterOperationId");

                    b.HasIndex("TypeId");

                    b.HasIndex("Id", "SequencePosition")
                        .IsUnique();

                    b.ToTable("OperationsParameters");
                });

            modelBuilder.Entity("Sptf.Domain.Models.OperationParameterType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("OperationParameterTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Integer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Text"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Boolean"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Date"
                        });
                });

            modelBuilder.Entity("Sptf.Domain.Models.Organizer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InputPlaylistId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OutputPlaylistId")
                        .HasColumnType("text");

                    b.Property<string>("OutputPlaylistName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Organizers");
                });

            modelBuilder.Entity("Sptf.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FilterOperationOrganizer", b =>
                {
                    b.HasOne("Sptf.Domain.Models.FilterOperation", null)
                        .WithMany()
                        .HasForeignKey("FilterOperationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sptf.Domain.Models.Organizer", null)
                        .WithMany()
                        .HasForeignKey("OrganizersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sptf.Domain.Models.OperationParameter", b =>
                {
                    b.HasOne("Sptf.Domain.Models.FilterOperation", null)
                        .WithMany("Parameters")
                        .HasForeignKey("FilterOperationId");

                    b.HasOne("Sptf.Domain.Models.OperationParameterType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Sptf.Domain.Models.Organizer", b =>
                {
                    b.HasOne("Sptf.Domain.Models.User", "User")
                        .WithMany("Organizers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sptf.Domain.Models.FilterOperation", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("Sptf.Domain.Models.User", b =>
                {
                    b.Navigation("Organizers");
                });
#pragma warning restore 612, 618
        }
    }
}
